### ISSUE TITLE
SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by crystalstorm466** [discordjs/discord.js-modules#75]
When deploying commands for discord.js an error occurs with the rest module.

`*PATH*\DiscordMusicBotJS\node_modules\@discordjs\rest\dist\lib\RequestManager.js:66
        const hash = this.hashes.get(`${request.method}:${routeID.bucketRoute}`) ?? `Global(${request.method}:${routeID.bucketRoute})`;`

I am getting a syntax error with the question mark as seen here: 
SyntaxError: Unexpected token '?'

I have tried removing the second question mark but I am still getting an error.

**Comment by Harsh8055git** [comment]
did it worked?
