### ISSUE TITLE
URLSearchParams with typescript on @discordjs/rest

### ISSUE THREAD

**Issue by yoyozbi** [discordjs/discord.js-modules#79]
### Issue description

Steps to reproduce:
1. Setup a typescript project (v4.4.4)
2. install @discordjs/rest 
3. import it and try to build

### Code sample

```typescript
import { REST } from "@discordjs/rest";
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

archlinux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_INTEGRATIONS, GUILD_INVITES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING

**Comment by yoyozbi** [comment]
i saw [here](https://stackoverflow.com/questions/63247242/how-to-use-urlsearchparams-in-a-node-js-and-typescript-project) that you may need to import URLSearchParams from url in order to use it with typescript

**Comment by Megatank58** [comment]
URLSearchParams is available on the global object in node.js 10+

**Comment by yoyozbi** [comment]
Sorry i didn't send the error message, here it is:
![image](https://user-images.githubusercontent.com/46626633/140536215-33db0260-73ba-4d9f-bed0-8ce32bf14c15.png)

**Comment by Megatank58** [comment]
Make sure you have `@types/node` and it's updated

**Comment by yoyozbi** [comment]
it is:
![image](https://user-images.githubusercontent.com/46626633/140536442-eefaa2e2-b686-4e28-954b-95837d2ddaef.png)

**Comment by Megatank58** [comment]
Could you try setting the `dom` option enabled in the `lib` configuration of `tsconfig.json` as [described here](https://stackoverflow.com/a/60258791)

**Comment by yoyozbi** [comment]
better now. Didn't made the best google research. Thanks !!
