### ISSUE TITLE
RequestManager Assumes JSON Body

### ISSUE THREAD

**Issue by ChrisTalman** [discordjs/discord.js-modules#90]
### Issue description

1. Attempt to execute a request on an endpoint which doesn't expect JSON, like `/oauth/token`.
2. A Discord API error is thrown, because the API is given an invalid body for the endpoint.

### Code sample

```typescript
const { REST } = '@discordjs/rest';

const body = new URLSearchParams();
body.set('client_id', '123');
REST.post('/oauth/token', {body, auth: false})
```

### discord.js version

0.1.0-canary.0

### Node.js version

16.13.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by ChrisTalman** [comment]
I'm not sure how this *should* be handled.

One approach could be for `resolveRequest()` to check whether `request.body instanceof URLSearchParams`. If so, the body could be left as it is, and the `Content-Type` header could be set to `application/x-www-form-urlencoded` in `additionalHeaders`. Otherwise, `request.body` would be treated as it is currently, as JSON.

**Comment by ckohen** [comment]
Turns out, we have almost no support for oauth endpoints, including the returned errors when trying to do this currently.
