### ISSUE TITLE
channelMessageOwnReaction API is not work

### ISSUE THREAD

**Issue by LiChangNan-Programmer** [discordjs/discord.js-modules#94]
### Issue description

I want to add reactions to the message with code, but this interface does not work。

### Code sample

```typescript
rest.put(
  Routes.channelMessageOwnReaction(
    channelId,
    reaction.message.id,
    decodeURIComponent(reaction.emoji.name)
  )
);
```

### discord.js version

13.3.1

### Node.js version

16.13.1

### Operating system

macOs

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INTEGRATIONS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGE_REACTIONS

**Comment by vladfrangu** [comment]
Thats not a bug in the rest module, your route is probably wrong. If it's a unicode emoji, you need to `encodeURIComponent()` it, if it's a custom emoji it needs to be in the format `name:id` (no encoding)

**Comment by LiChangNan-Programmer** [comment]
ohh, I will try

**Comment by LiChangNan-Programmer** [comment]
> Thats not a bug in the rest module, your route is probably wrong. If it's a unicode emoji, you need to `encodeURIComponent()` it, if it's a custom emoji it needs to be in the format `name:id` (no encoding)

I want to tell you that 🇩 is the emoji I am using, but I know if this is custom?

like this
![image](https://user-images.githubusercontent.com/81012489/146207585-fcd2b611-54c4-4b73-bf8a-b39d1f232272.png)

**Comment by vladfrangu** [comment]
That's an unicode emoji! Custom emojis are those that have ids (reaction.emoji.id). That should help you 👍

**Comment by LiChangNan-Programmer** [comment]
> 那是一个 unicode 表情符号！自定义表情符号是那些具有 id (reaction.emoji.id) 的表情符号。那应该对你有帮助👍

Thank you, I understand, but I just need to use this expression. So my initial code example should be normal logic?

**Comment by LiChangNan-Programmer** [comment]
oh sorry , it's encodeURIComponent

**Comment by vladfrangu** [comment]
You cannot react in someone else's name. Bots can only react in their own name... I cannot help you with your own code without getting a reproduction sample of code that shows the issue.

**Comment by LiChangNan-Programmer** [comment]
So that's it, it seems that this is really not a bug. I thought about it and thought that this concept was reasonable. It seemed that I had to find a way to adjust the demand. thank you for your help!
