### ISSUE TITLE
(@discordjs/rest) npm latest tag doesn't resolve to latest version

### ISSUE THREAD

**Issue by claabs** [discordjs/discord.js-modules#95]
### Issue description

Just running `npm i @discordjs/rest` doesn't install the latest version. Instead it installs `0.1.0-canary.0`, the oldest version.

![image](https://user-images.githubusercontent.com/6274312/146685454-dc8ad1ca-247b-4556-be46-28a8f9fabbe8.png)

It appears this is intentional behavior for [prerelease tags](https://github.com/npm/node-semver#prerelease-tags). However, how the updates are being released (updating the minor version rater than the prerelease version), the latest tag never gets updated.

The correct approach would probably be to just remove the prerelease tag, as it isn't being used.
Otherwise the [discordjs.guide](https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands) site should be updated to use `npm install @discordjs/rest@canary`.

### discord.js version

0.2.0-canary.0

### Node.js version

16

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by iCrawl** [comment]
This has been resolved.
